version: "3.8"

services:
#  must be a valid service on dockerhub
  mysqldb:
    container_name: mysqldb
    image: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myblog